"""Read a CloudFormation template's Parameters block and turn each parameter into a JSON
Schema property. This is the only place that translates CFN parameter constraints into JSON
Schema — generate.py calls it once per template, so the schemas can never see a constraint the
template does not also enforce.

===============================================================================================
VENDORED. Do not edit this file here.
===============================================================================================

The original is `deployment/schema/cfn_params.py` in the **private** `cu-aaii/aisei-agents` repo,
and that copy is authoritative. This one exists because a blueprint's `schema.json` has to be built
*here*, in this repo's CI, and this repo is public — so it cannot import from a private one.

Why a committed schema at all, rather than parsing the template at read time: the generated JSON is
plain draft-2020-12, with a template's `Rules:` compiled into `if`/`then`. So **any** consumer that
can validate JSON Schema can validate a blueprint config — `ajv`, `jsonschema`, a Go validator, a
form generator — and none of them needs a CloudFormation parser, a YAML tag table, or a copy of this
file. The parse happens once, at build time, in the one place that owns the templates. The Builder
Agent being TypeScript (`aisei-agents` D-84) is the first consumer to benefit, not the reason.

This file is therefore the *only* thing duplicated between the two repos, and it is on the producing
side. Nothing that consumes a schema is copied anywhere.

**Drift is caught, not trusted.** `aisei-agents`' own test suite asserts that this vendored copy
and its original produce byte-identical schemas for all six blueprints. A change made here and not
there — or there and not here — fails that gate. Fix the original first, then re-copy:

    cp ../aisei-agents/deployment/schema/cfn_params.py scripts/cfn_params.py
    # then restore this header, which the original does not carry
"""

from pathlib import Path
from typing import Any
import yaml


class _CfnLoader(yaml.SafeLoader):
    """Accepts CloudFormation's short-form intrinsic tags (!Sub, !Ref, !If, ...) as plain
    values, since parameter *definitions* never contain intrinsics — only Default/Type/etc.
    Needed anyway because the tags appear elsewhere in the same file.
    """


def _construct_intrinsic(loader: yaml.SafeLoader, suffix: str, node: yaml.Node) -> Any:
    if isinstance(node, yaml.ScalarNode):
        return loader.construct_scalar(node)
    if isinstance(node, yaml.SequenceNode):
        return loader.construct_sequence(node)
    return loader.construct_mapping(node)


_CfnLoader.add_multi_constructor('!', _construct_intrinsic)


def load_template_parameters(template_path: Path) -> dict[str, dict[str, Any]]:
    with open(template_path) as f:
        template = yaml.load(f, Loader=_CfnLoader)

    return template.get('Parameters', {})


class _CfnTaggedLoader(yaml.SafeLoader):
    """Like _CfnLoader but keeps the intrinsic's name: `!Equals [a, b]` loads as
    {'Equals': [a, b]}, `!Ref X` as {'Ref': 'X'}. The Rules block is made of intrinsics, so
    translating it needs to know which one it is looking at."""


def _construct_tagged(loader: yaml.SafeLoader, suffix: str, node: yaml.Node) -> Any:
    if isinstance(node, yaml.ScalarNode):
        value = loader.construct_scalar(node)
    elif isinstance(node, yaml.SequenceNode):
        value = loader.construct_sequence(node, deep=True)
    else:
        value = loader.construct_mapping(node, deep=True)
    return {suffix: value}


_CfnTaggedLoader.add_multi_constructor('!', _construct_tagged)


def load_template_rules(template_path: Path) -> dict[str, dict[str, Any]]:
    """The template's Rules block with intrinsics preserved as {'Equals': [...]} etc."""
    with open(template_path) as f:
        template = yaml.load(f, Loader=_CfnTaggedLoader)

    return template.get('Rules', {}) or {}


# CFN parameter Type -> JSON Schema {"type": ...}. Every config file on disk holds the value
# CloudFormation's API itself expects, which for List<String> is a single comma-joined string,
# not a JSON array — see deployment/aws/services/*/environments/*/service-pipeline-config.json.
# So every CFN parameter type maps to a JSON Schema string; List<String> gets no extra pattern
# because the delimited values (e.g. branch names) are otherwise unconstrained. Type: Number is
# also a string in the config (CreateStack takes ParameterValue as a string) — it gets a numeric
# pattern, and MinValue/MaxValue are carried into the description only, since JSON Schema cannot
# range-check a string.
_SSM_TYPE_PREFIX = 'AWS::SSM::Parameter::Value<'
# CloudFormation's `Number` is an integer **or** a float, and the float case is not hypothetical:
# Aurora Serverless v2 capacity is measured in ACU and 0.5 is the lowest always-warm setting, so an
# integer-only `^-?\d+$` rejected a valid postgres-aurora-serverless config. Found 2026-09-11 when
# the blueprints repo started generating schemas — no platform template happens to declare a
# fractional Number, which is why this went unnoticed. The exponent form is accepted too; CFN takes
# whatever its own Number validator does, and refusing `1e3` here would be a second false negative.
_NUMBER_PATTERN = r'^-?(?:\d+(?:\.\d+)?|\.\d+)(?:[eE][-+]?\d+)?$'


def param_to_json_schema(spec: dict[str, Any]) -> dict[str, Any]:
    schema: dict[str, Any] = {'type': 'string'}
    description_parts: list[str] = []
    # A parameter can attract more than one pattern — an SSM-typed or Number type contributes
    # one, and AllowedPattern contributes another. JSON Schema allows a single "pattern" per
    # schema object, so a second assignment would silently drop the first: an SSM-typed
    # parameter with AllowedPattern would stop requiring the leading '/'. Collect them and
    # combine with allOf when there is more than one, so every pattern still has to hold.
    patterns: list[str] = []

    cfn_type = spec.get('Type', 'String')
    if cfn_type.startswith(_SSM_TYPE_PREFIX):
        # The config file holds an SSM parameter *name*, resolved by CloudFormation at deploy
        # time — every one committed so far is an absolute path.
        patterns.append('^/')

    if cfn_type == 'Number':
        patterns.append(_NUMBER_PATTERN)
        bounds = []
        if 'MinValue' in spec:
            bounds.append(f'>= {spec["MinValue"]}')
        if 'MaxValue' in spec:
            bounds.append(f'<= {spec["MaxValue"]}')
        description_parts.append(
            'CFN Type: Number, written as a string in the config'
            + (f' ({", ".join(bounds)})' if bounds else '')
            + '.'
        )

    if 'AllowedPattern' in spec:
        # CFN's AllowedPattern must match the *entire* value; JSON Schema's "pattern" only
        # requires a match somewhere in the string. Anchoring closes that gap — unanchored,
        # "Bad_Name!" still validates against "[a-z0-9-]{1,20}" via the "ad-name" substring.
        patterns.append(f"^(?:{spec['AllowedPattern']})$")

    if len(patterns) == 1:
        schema['pattern'] = patterns[0]
    elif patterns:
        schema['allOf'] = [{'pattern': pattern} for pattern in patterns]

    if 'AllowedValues' in spec:
        schema['enum'] = [str(value) for value in spec['AllowedValues']]
    if 'MinLength' in spec:
        schema['minLength'] = int(spec['MinLength'])
    if 'MaxLength' in spec:
        schema['maxLength'] = int(spec['MaxLength'])

    if 'Default' in spec:
        # The value CloudFormation uses when the key is omitted — as a string, like every
        # other value in a config file. None is YAML's reading of a bare `Default:`.
        default = spec['Default']
        schema['default'] = '' if default is None else str(default)

    if spec.get('NoEcho') in (True, 'true'):
        # JSON Schema's annotation for "do not display back"; the value is masked in the
        # CloudFormation console and API too.
        schema['writeOnly'] = True
        description_parts.append('NoEcho: the value is masked by CloudFormation.')

    if 'Description' in spec:
        description_parts.insert(0, str(spec['Description']))
    if 'ConstraintDescription' in spec:
        description_parts.append(f'Constraint: {spec["ConstraintDescription"]}')

    if description_parts:
        schema['description'] = ' '.join(description_parts)

    return schema


def is_required(spec: dict[str, Any]) -> bool:
    """A CFN parameter with no Default must be supplied by the config file — CloudFormation
    rejects CreateStack/UpdateStack otherwise."""
    return 'Default' not in spec


# Rules -> JSON Schema
#
# CloudFormation evaluates a template's Rules block only when a stack is created or updated —
# a change set does NOT evaluate it (verified against a live account 2026-09-09: a change set
# whose Rules would fail reaches CREATE_COMPLETE, and the assertion fires on execute, as a
# fast ROLLBACK before any resource is created). So an offline validator that wants to catch
# "attach mode with a blank ExistingVpcId" has to mirror the Rules itself. This translates the
# one shape the templates use and refuses anything else, so a new Rule that cannot be mirrored
# fails generate.py (and CI) instead of silently going unchecked:
#
#   RuleCondition:  !Equals [!Ref X, 'v']
#                   !Not [!Equals [!Ref X, '']]               # "when X is set at all"
#                   !And [ <condition>, ... ]  /  !Or [ <condition>, ... ]
#   Assertions:     - Assert: !Not [!Equals [!Ref Y, '']]      # "Y must be non-empty"
#
# Long-form `Fn::Equals` is accepted everywhere the short form is — they are the same intrinsic, and
# a `!Not` wrapping a `!Equals` cannot be written in short form without quoting, so a template that
# nests them uses the long form. See _intrinsic.
#
# Each rule becomes one {"if": ..., "then": ...} entry in the Parameters schema's allOf.

class UnsupportedRule(ValueError):
    pass


def _intrinsic(node: Any) -> tuple[str | None, Any]:
    """(the intrinsic's short name, its argument) for a one-key intrinsic mapping, else (None, node).

    `!Equals [a, b]` and the long form `Fn::Equals: [a, b]` are the same thing to CloudFormation, and
    a template may use either — dynamodb-table's Rules use the long form because a `!Not` wrapping a
    `!Equals` cannot be written in short form without quoting. So normalise here rather than at each
    call site, where forgetting it means the Rule silently fails to translate. `Ref` has no `Fn::`
    prefix, which is why the prefix is stripped rather than required.
    """
    if isinstance(node, dict) and len(node) == 1:
        key = next(iter(node))
        if isinstance(key, str):
            return key[4:] if key.startswith('Fn::') else key, node[key]
    return None, node


def _ref_name(node: Any, rule_name: str) -> str:
    name, argument = _intrinsic(node)
    if name == 'Ref' and isinstance(argument, str):
        return argument
    raise UnsupportedRule(f'Rule {rule_name}: expected !Ref <Parameter>, got {node!r}')


def _equals_parameter_value(node: Any, rule_name: str) -> tuple[str, str]:
    name, argument = _intrinsic(node)
    if name == 'Equals' and isinstance(argument, list) and len(argument) == 2:
        left, right = argument
        if isinstance(right, str):
            return _ref_name(left, rule_name), right
    raise UnsupportedRule(f'Rule {rule_name}: only `!Equals [!Ref <Parameter>, <string>]` is supported, got {node!r}')


def _not_argument(node: Any, rule_name: str) -> Any:
    """The single operand of a `!Not [...]`, or None when this is not a Not."""
    name, argument = _intrinsic(node)
    if name != 'Not':
        return None
    if isinstance(argument, list) and len(argument) == 1:
        return argument[0]
    raise UnsupportedRule(f'Rule {rule_name}: !Not takes exactly one operand, got {node!r}')


def _condition_schema(node: Any, parameters: dict[str, dict[str, Any]], rule_name: str) -> dict[str, Any]:
    intrinsic, argument = _intrinsic(node)

    if intrinsic == 'And':
        return {'allOf': [_condition_schema(part, parameters, rule_name) for part in argument]}
    if intrinsic == 'Or':
        return {'anyOf': [_condition_schema(part, parameters, rule_name) for part in argument]}

    negated = _not_argument(node, rule_name)
    if negated is not None:
        # `!Not [!Equals [!Ref X, '']]` as a *condition* -- "this rule applies when X is set", which
        # is how an optional-parameter-implies-another rule is written. JSON Schema's `not` is the
        # exact mirror, with one wrinkle handled by _condition_schema below it: a parameter whose
        # Default is '' satisfies `X == ''` when the key is omitted, so `not(X == '')` must also
        # require the key to be present.
        return {'not': _condition_schema(negated, parameters, rule_name)}

    name, value = _equals_parameter_value(node, rule_name)
    if name not in parameters:
        raise UnsupportedRule(f'Rule {rule_name}: {name} is not a template parameter')

    present_and_equal = {'required': [name], 'properties': {name: {'const': value}}}

    default = parameters[name].get('Default')
    default = '' if default is None else str(default)
    if 'Default' in parameters[name] and default == value:
        # Omitting the key in the config means CloudFormation uses the Default, which
        # satisfies the condition — so an absent key must also select the `then` branch.
        return {'anyOf': [{'not': {'required': [name]}}, present_and_equal]}

    return present_and_equal


def _default_satisfies(spec: dict[str, Any], forbidden: str) -> bool:
    """True when omitting this parameter still satisfies `!Not [!Equals [!Ref X, <forbidden>]]`,
    because CloudFormation substitutes the Default before evaluating Rules. A bare `Default:` loads
    as None, which is the empty string to CloudFormation; no Default at all means the value must be
    supplied, so omitting it satisfies nothing."""
    if 'Default' not in spec:
        return False
    default = spec['Default']
    return ('' if default is None else str(default)) != forbidden


def _assertion_forbidden_value(assertion: dict[str, Any], rule_name: str) -> tuple[str, str]:
    """(parameter, value it must not have) for one `!Not [!Equals [!Ref X, <string>]]` assertion.

    The empty string is the common case — "X must be set" — and is what every assertion in this
    repository said until the agent block. `!Not [!Equals [!Ref AgentAdmin, 'false']]` is the same
    shape with a non-empty value, meaning "X must not be false", and it translates just as exactly;
    the two differ only in what the `then` branch asserts. Anything else raises, because a Rule this
    translator silently skipped would be a Rule with no pre-deploy check at all — see the module
    docstring on why that matters more here than the shape of the code.
    """
    node = assertion.get('Assert')
    negated = _not_argument(node, rule_name)
    if negated is not None:
        return _equals_parameter_value(negated, rule_name)
    raise UnsupportedRule(f'Rule {rule_name}: only `!Not [!Equals [!Ref <Parameter>, <string>]]` assertions are supported, got {node!r}')


def rules_to_json_schema(rules: dict[str, dict[str, Any]], parameters: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    """One if/then subschema per Rule, in template order. Raises UnsupportedRule for a shape
    this translator does not understand — extend it rather than skip the rule."""
    subschemas = []
    for rule_name, rule in rules.items():
        described: dict[str, tuple[str, str]] = {}
        for assertion in rule.get('Assertions', []):
            name, forbidden = _assertion_forbidden_value(assertion, rule_name)
            description = str(assertion.get('AssertDescription', '')) or (
                f'{name} must not be "{forbidden}" (Rule {rule_name})' if forbidden
                else f'{name} is required by Rule {rule_name}'
            )
            described[name] = (forbidden, description)

        # An assertion says what the *deployed* value must not be, which is not the same as "the
        # config file must carry the key". A parameter whose Default already satisfies the assertion
        # satisfies it when the key is omitted — CloudFormation substitutes the Default before
        # evaluating Rules — so demanding it in the config would reject a config the deploy accepts.
        # Mirrors _condition_schema's handling of a condition satisfied by a Default.
        required = sorted(
            name for name, (forbidden, _) in described.items()
            if not _default_satisfies(parameters.get(name, {}), forbidden)
        )
        then: dict[str, Any] = {
            'required': required,
            'properties': {
                # Two shapes, because "must not be empty" and "must not be this particular value"
                # are different assertions. `minLength: 1` is kept for the empty case rather than
                # unified into `not: {const: ''}` — it produces a readable error ("'' is too short")
                # and it is what every committed schema already contains.
                name: (
                    {'minLength': 1, '$comment': description} if forbidden == ''
                    else {'not': {'const': forbidden}, '$comment': description}
                )
                for name, (forbidden, description) in sorted(described.items())
            },
        }
        subschema: dict[str, Any] = {
            '$comment': f'CFN Rule {rule_name}',
            'then': then,
        }
        if 'RuleCondition' in rule:
            subschema['if'] = _condition_schema(rule['RuleCondition'], parameters, rule_name)
        else:
            subschema['if'] = True  # unconditional rule

        subschemas.append(subschema)
    return subschemas
